stages:
  - build

build:
  stage: build
  only:
    refs:
      - develop
  script:
    - cd /htdocs/dynamic-form
    - git pull
    - yarn --registry=https://registry.npmmirror.com
    - yarn build:docs
  tags:
    - my-runner
