name: Node.js CI

on:
  push:
    paths:
     - 'packages/package.json'

jobs:
  publish-npm:

    runs-on: macos-latest

    # 任务的步骤
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - run: yarn
    - shell: bash
      run: ./build-lib.sh
    - run: cd packages && npm publish --access public

      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
